#./k8s/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-nginx-deployment #deployment 이름으로 위의 Secrets에 입력한 값과 동일하게 맞춘다.
spec:
  replicas: 3
  selector:
    matchLabels:
      app: react-test #자유롭게 설정
  template:
    metadata:
      labels:
        app: react-test #자유롭게 설정
    spec:
      containers:
        - name: react-test #자유롭게 설정
          image: gcr.io/yapp16-findzone/react-test:latest #image 위치로 추후 동적으로 변경하나 프로젝트-이미지 이름으로 미리 설정해준다.
          ports:
            - containerPort: 80
