#./k8s/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: react-test #Kubernetes Engine-서비스 및 수신에 생성될 이름이다.
  labels:
    app: react-test #자유롭게 설정
spec:
  ports:
    - name: '80'
      port: 80
      targetPort: 80
  selector:
    app: react-test #deployment에서 containers.name과 동일하게 설정한다.
  type: LoadBalancer
